# DNS upstream (pour les requêtes internet normales)
server=1.1.1.1
server=8.8.8.8

# Ton nom de domaine local → IP de ton PC
# ⚠️ Remplace 192.168.1.100 par ta vraie IP fixe plus tard
address=/local-bwa/192.168.1.14

# Log des requêtes (utile pour déboguer)
log-queries